//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
//

#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

// ------------------- Function Prototypes --------------------

int64_t __do_global_dtors_aux(void);
int64_t _fini(void);
int64_t _init(void);
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6);
int64_t deregister_tm_clones(void);
int64_t frame_dummy(void);
void function_1090(int64_t * d);
void function_10a0(int64_t * ptr);
char * function_10b0(char * dest, char * src);
void function_10c0(void);
int32_t function_10d0(char * format, ...);
int32_t function_10e0(int32_t fd, int64_t * buf, int32_t nbytes);
int64_t * function_10f0(int32_t size);
int64_t register_tm_clones(void);

// --------------------- Global Variables ---------------------

int64_t g1 = 0; // 0x4010
int32_t g2;

// ------- Dynamically Linked Functions Without Header --------

void __cxa_finalize(int64_t * a1);
void __gmon_start__(void);
int32_t __libc_start_main(int64_t a1, int32_t a2, char ** a3, void (*a4)(), void (*a5)(), void (*a6)());
void __stack_chk_fail(void);

// ------------------------ Functions -------------------------

// Address range: 0x1000 - 0x101b
int64_t _init(void) {
    int64_t result = 0; // 0x1012
    if (*(int64_t *)0x3fe8 != 0) {
        // 0x1014
        __gmon_start__();
        result = &g2;
    }
    // 0x1016
    return result;
}

// Address range: 0x1090 - 0x109b
void function_1090(int64_t * d) {
    // 0x1090
    __cxa_finalize(d);
}

// Address range: 0x10a0 - 0x10ab
void function_10a0(int64_t * ptr) {
    // 0x10a0
    free(ptr);
}

// Address range: 0x10b0 - 0x10bb
char * function_10b0(char * dest, char * src) {
    // 0x10b0
    return strcpy(dest, src);
}

// Address range: 0x10c0 - 0x10cb
void function_10c0(void) {
    // 0x10c0
    __stack_chk_fail();
}

// Address range: 0x10d0 - 0x10db
int32_t function_10d0(char * format, ...) {
    // 0x10d0
    return printf(format);
}

// Address range: 0x10e0 - 0x10eb
int32_t function_10e0(int32_t fd, int64_t * buf, int32_t nbytes) {
    // 0x10e0
    return read(fd, buf, nbytes);
}

// Address range: 0x10f0 - 0x10fb
int64_t * function_10f0(int32_t size) {
    // 0x10f0
    return malloc(size);
}

// Address range: 0x1100 - 0x1126
int64_t _start(int64_t a1, int64_t a2, int64_t a3, int64_t a4, int64_t a5, int64_t a6) {
    // 0x1100
    int64_t v1; // 0x1100
    __libc_start_main(0x11e9, (int32_t)a6, (char **)&v1, NULL, NULL, (void (*)())a3);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x1130 - 0x1159
int64_t deregister_tm_clones(void) {
    // 0x1130
    return &g1;
}

// Address range: 0x1160 - 0x1199
int64_t register_tm_clones(void) {
    // 0x1160
    return 0;
}

// Address range: 0x11a0 - 0x11d9
int64_t __do_global_dtors_aux(void) {
    // 0x11a0
    if (*(char *)&g1 != 0) {
        // 0x11d8
        int64_t result; // 0x11a0
        return result;
    }
    // 0x11ad
    if (*(int64_t *)0x3ff8 != 0) {
        // 0x11bb
        __cxa_finalize((int64_t *)*(int64_t *)0x4008);
    }
    int64_t result2 = deregister_tm_clones(); // 0x11c7
    *(char *)&g1 = 1;
    return result2;
}

// Address range: 0x11e0 - 0x11e9
int64_t frame_dummy(void) {
    // 0x11e0
    return register_tm_clones();
}

// Address range: 0x11e9 - 0x128f
int main(int argc, char ** argv) {
    int64_t v1 = __readfsqword(40); // 0x11f5
    printf("what do you what to say");
    int64_t buf; // bp-72, 0x11e9
    read(0, &buf, 64);
    int64_t * mem = malloc(64); // 0x1238
    strcpy((char *)mem, (char *)&buf);
    free(mem);
    free(mem);
    int64_t result = 0; // 0x1286
    if (v1 != __readfsqword(40)) {
        // 0x1288
        __stack_chk_fail();
        result = &g2;
    }
    // 0x128d
    return result;
}

// Address range: 0x1290 - 0x129d
int64_t _fini(void) {
    // 0x1290
    int64_t result; // 0x1290
    return result;
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (13.1.0)
// Detected functions: 15

